### ISSUE TITLE
Telemetry provider implementation for micrometer

### ISSUE THREAD

**Issue by monosoul** [smithy-lang/smithy-kotlin#1087]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

`TelemetryProvider` implementation to publish metrics using [micrometer](https://micrometer.io/)

## Is your Feature Request related to a problem?

It would be great if alongside the [OTel implementation](https://github.com/smithy-lang/smithy-kotlin/tree/main/runtime/observability/telemetry-provider-otel), there was also a micrometer implementation. Unfortunately, there's no adapter from OTel API to micrometer, there's no way to use OTel telemetry provider with micrometer.

## Proposed Solution

Provide `TelemetryProvider` implementation usable with `micrometer`

## Additional Context

This is a duplicate of https://github.com/awslabs/aws-sdk-kotlin/issues/1301, since I wasn't sure where it's better to create this issue. Feel free to close the one that's in the wrong place :slightly_smiling_face: 

- [ ] I may be able to implement this feature request

**Comment by ianbotsf** [comment]
@monosoul thanks for opening this feature request, Micrometer looks cool. We can't prioritize this just yet but we'll leave it open so others can 👍+1  it.

I see you've made some contributions to the Micrometer GH repository so you've clearly got some familiarity...if you'd like to contribute a pull request to enable this feature, please feel free!

The telemetry interfaces/implementations live in **smithy-kotlin** not **aws-sdk-kotlin** so I'll be closing [the other issue you opened](https://github.com/awslabs/aws-sdk-kotlin/issues/1301) in favor of this one.

**Comment by monosoul** [comment]
Hey @ianbotsf , I took a quick look at the API you have for telemetry providers and it seems like interfaces there are heavily influenced by OTel implementation. Not yet sure if I'll be able to introduce micrometer implementation without touching some of those interfaces, therefore I was hoping someone more familiar with the code base will take a look into that 😅
I might give it a try too tho 🤔

**Comment by ianbotsf** [comment]
Yes, those interfaces in [**telemetry-api**](https://github.com/smithy-lang/smithy-kotlin/tree/main/runtime/observability/telemetry-api) are pretty much fixed and won't likely be changed. New implementations will have to conform themselves to those interfaces, ignoring the features they can't support, using extra configuration options/extensions to support features not modeled in the telemetry API, etc.

If you're an existing user of both the AWS SDK for Kotlin and Micrometer then you're likely in the best position to at least _start_ on an implementation—even one that's narrowly tailored to your specific use case. If it's generalizable enough then a PR might be warranted. Feel free to reach out with questions about the existing interfaces and the current implementation for OTel.

**Comment by monosoul** [comment]
Okay, I hacked for a bit and this might work I think: https://github.com/smithy-lang/smithy-kotlin/pull/1089
