### ISSUE TITLE
https.nonProxyHosts does not handle * wildcard

### ISSUE THREAD

**Issue by grassehh** [smithy-lang/smithy-kotlin#1092]
### Describe the bug

The * wildcard does not work when using `https.nonProxyHosts`

### Expected behavior

As described in the [Java specifications](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html):
_http.nonProxyHosts:a list of hosts that should be reached directly, bypassing the proxy. This is a list of patterns separated by '|'. **The patterns may start or end with a '*' for wildcards**. Any host matching one of these patterns will be reached through a direct connection instead of through a proxy._

So when configuring a host which starts or ends with a * wildcard should match. For example:
`my.host` should both match the non proxy hosts `*.host` and `my.*`

### Current behavior

The host does not match non proxy hosts when using *.
For example: `my.host` won't match the non proxy hosts `*.host` and `my.*`

### Steps to Reproduce

Simply configure a client using environment while having defined `*.host` in `http.nonProxyHosts` system property. For example:
```kotlin
S3Client.fromEnvironment {}
```
Then if you make a request to the host `my-host` defined in the system property, the http client will still try to go through the proxy because it has not matched the non proxy host.

### Possible Solution

Fix [this method](https://github.com/smithy-lang/smithy-kotlin/blob/f67fc02a0c74c48aefd7f1996085e1090351ebfb/runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelector.kt#L99) so that it handle `hostMatch` that starts or ends with * wildcard

### Smithy-Kotlin version

1.2.2

### Platform (JVM/JS/Native)

Java 21

### Operating system and version

Debian 12

**Comment by ianbotsf** [comment]
Thanks for the bug report, @grassehh! We've merged a fix to **main** and we'll work on getting it out in tomorrow's SDK release.
