### ISSUE TITLE
Check for empty proxy hosts

### ISSUE THREAD

**Issue by ScottRoo** [smithy-lang/smithy-kotlin#1098]
### Describe the bug

We're seeing the following issue in our logs which I've tracked down to `EnvironmentProxySelector`

`Caused by: aws.smithy.kotlin.runtime.ClientException: Could not parse http.proxyHost="", http.proxyPort="0" into a valid proxy URL`

### Expected behavior

Ideally the `EnvironmentProxySelector` would check the length of the proxy host before attempting to use it, like `DefaultProxySelector` does [here](https://github.com/frohoff/jdk8u-jdk/blob/da0da73ab82ed714dc5be94acd2f0d00fbdfe2e9/src/share/classes/sun/net/spi/DefaultProxySelector.java#L225)

### Current behavior

If SQS detects an value for `proxy_host`, even if it's empty, it will attempt to use it and the connection will fail.

### Steps to Reproduce

I'm not entirely sure how this is being set in the wild, but we've been able to reproduce it by setting the property before initialising the SQS client

`System.setProperty("http.proxyHost", "")`

### Possible Solution

Check the length of the host value before using the proxy settings

### Smithy-Kotlin version

1.25

### Platform (JVM/JS/Native)

JVM

### Operating system and version

Android 8/9/10

**Comment by ianbotsf** [comment]
Hi @ScottRoo, thanks for the bug report. I've merged a PR to address empty/blank proxy hosts and it should be available in tomorrow's **aws-sdk-kotlin** release **v1.2.28**.

**Comment by ScottRoo** [comment]
Amazing, thanks for the quick turnaround @ianbotsf
