### ISSUE TITLE
OkHttp4 Support Broken Due to Idle Connection PR

### ISSUE THREAD

**Issue by Rostifar** [smithy-lang/smithy-kotlin#1176]
### Describe the bug

A recent [PR](https://github.com/smithy-lang/smithy-kotlin/pull/1171/files) was merged, which requires [ConnectionListener](https://github.com/smithy-lang/smithy-kotlin/pull/1171/files#diff-75872e76cfe5cafdc473fe3016292828fea83e9d314d8605202bcfa92a230b73R103) support to function correctly. 

ConnectionListener was introduced in [OkHttp 5.x](https://square.github.io/okhttp/changelogs/changelog/#version-500-alpha12), so this change will break OkHttp 4.x support. 

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected behavior

Building an [OkHttpEngine4](https://github.com/smithy-lang/smithy-kotlin/tree/main/runtime/protocol/http-client-engines/http-client-engine-okhttp4) instance should not require any OkHttp 5.x concepts.

### Current behavior

Instantiating `OkHttpEngine4` will lead to a `ClassNotFoundException` exception for `ConnectionListener` when `config.buildClient(...)` is [called](https://github.com/smithy-lang/smithy-kotlin/blob/03cdfb45610b3b0a98fb481a24f598b9f5726ea0/runtime/protocol/http-client-engines/http-client-engine-okhttp4/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp4/OkHttp4Engine.kt#L48).  

### Steps to Reproduce

Configure a OkHttp4Engine in accordance with [these](https://github.com/smithy-lang/smithy-kotlin/tree/main/runtime/protocol/http-client-engines/http-client-engine-okhttp4) instructions:
```
import aws.smithy.kotlin.runtime.http.engine.okhttp4.OkHttp4Engine
val client = OkHttp4Engine()
```
Use http-client-engine-okhttp4 v1.3.20 to reproduce. 

### Smithy-Kotlin version

aws.smithy.kotlin:http-client-engine-okhttp4:1.3.20

### Platform (JVM/JS/Native)

JVM

### Operating system and version

Ubuntu 20.04

**Comment by 0marperez** [comment]
Hello, thanks for reporting this issue. We have a PR up now that should fix it.
