### ISSUE TITLE
Investigate adding DslMarker annotations to public APIs for better suggestions

### ISSUE THREAD

**Issue by kggilmer** [smithy-lang/smithy-kotlin#428]
The `DslMarker` annotation was mentioned by JetBrains as a way we can influence type suggestions in Intellij.  It was mentioned that this annotation is not stable so we cannot count on it.  We could provide feedback back to JB to prioritize stabilization but first we should know:

1. how much does stability matter w/ something like this?
2. does application of the annotation meaningfully improve the customer IDE experience

**Comment by ianbotsf** [comment]
`@DslMarker` appears to be stable at this time.
