### ISSUE TITLE
Allow customizing retry options for waiters

### ISSUE THREAD

**Issue by aajtodd** [smithy-lang/smithy-kotlin#839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

Waiters are generated as `wait<Action>(input: <InputType>): Outcome<OutputType>`. Internally the retry strategy token bucket, max attempts, and other options are hard coded (some come from the waiters spec). It would be useful to allow customizing/overriding some of the retry parameters (e.g. set higher or lower max attempts, delay parameters, etc).

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by ianbotsf** [comment]
Implemented by @lauzadis in #1183. Resolving as fixed.
